-- V1 — initial schema
-- All UUIDs are generated by the application layer.

CREATE TYPE location_type AS ENUM ('RESERVE', 'AISLE');
CREATE TYPE movement_type AS ENUM ('IN', 'OUT', 'TRANSFER', 'ADJUSTMENT');

-- ---------------------------------------------------------------
-- product
-- ---------------------------------------------------------------
CREATE TABLE product (
    id         UUID         NOT NULL DEFAULT gen_random_uuid(),
    ean        VARCHAR(13)  NOT NULL,
    name       VARCHAR(255) NOT NULL,
    category   VARCHAR(100),
    unit       VARCHAR(20)  NOT NULL DEFAULT 'UNIT',
    vat_rate   NUMERIC(5, 2) NOT NULL DEFAULT 20.00,
    active     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_product PRIMARY KEY (id),
    CONSTRAINT uq_product_ean UNIQUE (ean)
);

-- ---------------------------------------------------------------
-- location
-- ---------------------------------------------------------------
CREATE TABLE location (
    id         UUID          NOT NULL DEFAULT gen_random_uuid(),
    store_code VARCHAR(20)   NOT NULL,
    name       VARCHAR(255)  NOT NULL,
    type       location_type NOT NULL,
    active     BOOLEAN       NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_location PRIMARY KEY (id),
    CONSTRAINT uq_location_store_name UNIQUE (store_code, name)
);

-- ---------------------------------------------------------------
-- stock_item  (current qty per product × location)
-- ---------------------------------------------------------------
CREATE TABLE stock_item (
    id          UUID    NOT NULL DEFAULT gen_random_uuid(),
    product_id  UUID    NOT NULL,
    location_id UUID    NOT NULL,
    quantity    INTEGER NOT NULL DEFAULT 0 CHECK (quantity >= 0),
    CONSTRAINT pk_stock_item PRIMARY KEY (id),
    CONSTRAINT uq_stock_item_product_location UNIQUE (product_id, location_id),
    CONSTRAINT fk_stock_item_product  FOREIGN KEY (product_id)  REFERENCES product (id),
    CONSTRAINT fk_stock_item_location FOREIGN KEY (location_id) REFERENCES location (id)
);

-- ---------------------------------------------------------------
-- stock_movement  (immutable audit trail)
-- ---------------------------------------------------------------
CREATE TABLE stock_movement (
    id               UUID          NOT NULL DEFAULT gen_random_uuid(),
    type             movement_type NOT NULL,
    product_id       UUID          NOT NULL,
    from_location_id UUID,
    to_location_id   UUID,
    quantity         INTEGER       NOT NULL CHECK (quantity > 0),
    reason           TEXT,
    supplier_ref     VARCHAR(100),
    created_at       TIMESTAMPTZ   NOT NULL DEFAULT now(),
    created_by       VARCHAR(100)  NOT NULL,
    CONSTRAINT pk_stock_movement PRIMARY KEY (id),
    CONSTRAINT fk_movement_product       FOREIGN KEY (product_id)       REFERENCES product (id),
    CONSTRAINT fk_movement_from_location FOREIGN KEY (from_location_id) REFERENCES location (id),
    CONSTRAINT fk_movement_to_location   FOREIGN KEY (to_location_id)   REFERENCES location (id)
);

-- indexes for common queries
CREATE INDEX idx_stock_movement_product   ON stock_movement (product_id);
CREATE INDEX idx_stock_movement_created   ON stock_movement (created_at DESC);
CREATE INDEX idx_stock_item_product       ON stock_item (product_id);
CREATE INDEX idx_stock_item_location      ON stock_item (location_id);
